# Model Building

## Implementing Formula on our Dataset

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('FinalDataset.csv')
df.head()

Unnamed: 0  amount_of_loan  interest_rate  time_to_repay  simple_interest  \
0           0         2194341             10              8                0   
1           1         8639411              6              7                1   
2           2         7205196             13              5                0   
3           3         4041602              7              6                1   
4           4         9191103              6              5                1   

   cibil_score  past_debt_to_repay  profit_percentage_last_year  \
0          866             2626136                           34   
1          379             3530079                            1   
2          607               13704                           25   
3          631              760740                           46   
4          549             4239769                           28   

   competition_scale  sustainability  startup  management_effectivity  \
0                  8               0        0                       0   
1                  3               0        0                       1   
2                 10               1        1                       0   
3                 10               1        1                       1   
4                  8               1        0                       1   

   Total_Revenue  
0       10947810  
1        9260780  
2        6526200  
3       11793880  
4       10932480

In [3]:
df.drop(columns = ['Unnamed: 0'], inplace = True)
df.head()

amount_of_loan  interest_rate  time_to_repay  simple_interest  cibil_score  \
0         2194341             10              8                0          866   
1         8639411              6              7                1          379   
2         7205196             13              5                0          607   
3         4041602              7              6                1          631   
4         9191103              6              5                1          549   

   past_debt_to_repay  profit_percentage_last_year  competition_scale  \
0             2626136                           34                  8   
1             3530079                            1                  3   
2               13704                           25                 10   
3              760740                           46                 10   
4             4239769                           28                  8   

   sustainability  startup  management_effectivity  Total_Revenue  
0               0        0                       0       10947810  
1               0        0                       1        9260780  
2               1        1                       0        6526200  
3               1        1                       1       11793880  
4               1        0                       1       10932480

## Calculating Risk Factor

In [4]:
from LoanCostFunction import loan_cost_prediction

In [5]:
risk = []
cnt = 0
for i in range(0, 3000):
    risk.append(loan_cost_prediction(df['Total_Revenue'][i], df['profit_percentage_last_year'][i], df['simple_interest'][i], df['interest_rate'][i], df['amount_of_loan'][i], df['time_to_repay'][i], df['past_debt_to_repay'][i], df['sustainability'][i], df['competition_scale'][i], df['management_effectivity'][i], df['startup'][i], df['cibil_score'][i]))
     

In [6]:
df['Risk_Factor'] = risk
df.head()

amount_of_loan  interest_rate  time_to_repay  simple_interest  cibil_score  \
0         2194341             10              8                0          866   
1         8639411              6              7                1          379   
2         7205196             13              5                0          607   
3         4041602              7              6                1          631   
4         9191103              6              5                1          549   

   past_debt_to_repay  profit_percentage_last_year  competition_scale  \
0             2626136                           34                  8   
1             3530079                            1                  3   
2               13704                           25                 10   
3              760740                           46                 10   
4             4239769                           28                  8   

   sustainability  startup  management_effectivity  Total_Revenue  Risk_Factor  
0               0        0                       0       10947810            2  
1               0        0                       1        9260780           -2  
2               1        1                       0        6526200           -2  
3               1        1                       1       11793880           -2  
4               1        0                       1       10932480           -2

## Model Training

In [7]:
target = df.iloc[:, -1]

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(df.drop('Risk_Factor',axis='columns'), target, test_size=0.3)

In [9]:
reg = linear_model.LinearRegression()
reg.fit(df[['amount_of_loan', 'interest_rate', 'time_to_repay', 'simple_interest', 'cibil_score', 'past_debt_to_repay', 'profit_percentage_last_year', 'competition_scale', 'sustainability', 'startup', 'management_effectivity', 'Total_Revenue']], df['Risk_Factor'])


LinearRegression()

## Predicting Testcases

### Risk Factor is towards 2 (High Profit)

In [10]:
reg.predict([[2200000, 10, 7, 0, 880, 2600000, 40, 10, 0, 0, 0, 15000000]])

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1.13732073])

### Risk Factor is towards -2 (High Loss)

In [11]:
reg.predict([[8650000, 6, 8, 1, 400, 3500000, 1, 3, 0, 0, 1, 9260000]])

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-2.21207981])

### Risk Factor is towards 1 (Less Profit)

In [12]:
reg.predict([[3730000, 12, 2, 0, 700, 435000, 50, 2, 1, 1, 0, 8020000]])

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.91867856])

### Risk Factor is towards -1 (Less Profit)

In [13]:
reg.predict([[8350000, 13, 6, 0, 890, 10000000, 35, 9, 1, 1, 1, 5000000]])

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-0.27929969])